# vi: ft=swayconfig

# monitors
workspace $ws1 output DP-2
workspace $ws2 output HDMI-A-2

output DP-2 mode 2560x1440@240Hz pos 1920 0
output HDMI-A-2 mode 1920x1080@240Hz pos 0 0

# run streamdeck
exec --no-startup-id exec "$HOME/lib/streamdeck.py"
output * bg "$HOME/media/Pictures/Wallpapers/hqny4sv6ikv51.jpg" fill
