#!/usr/bin/env bash

set -eu -o pipefail

payload="$(base64 | tr -d '\n')"
seq=$'\033]52;c;'"$payload"$'\a'

if [[ -n "${TMUX:-}" ]]; then
    seq=$'\033Ptmux;'"${seq//$'\033'/$'\033\033'}"$'\033\\'
fi

printf '%s' "$seq"

exit
#!/usr/bin/env bash

set -eu -o pipefail

case "${XDG_SESSION_TYPE-}" in
    x11) xclip -selection clipboard "$@" ;;
    wayland) wl-copy "$@" ;;
    *)
        if [[ "$(uname)" == Darwin ]]; then
            pbcopy "$@"
        fi
        ;;
esac
