#!/usr/bin/env bash

set -eu -o pipefail

yay -Syy --noconfirm --needed \
    sway \
    grim \
    slurp \
    swaybg \
    wl-clipboard \
    sway-alttab-bin \
    wdisplays \
    swaylock \
    swayidle \
    xdg-desktop-portal-wlr \
    waybar \
    gammastep \
    sway-contrib \
    gtk4-layer-shell \

