
[terminal.shell]
program = "tmux"

# only works IF in transparent mode using a compositor like picom
#[window]
#opacity = 0.4

# my epic font choice
[font]
size = 15
# or Comic Mono
[font.bold]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font Mono"
style = "Regular"

# needed for colours
[env]
TERM = "xterm-256color"

# this is some hack to send raw characters to tmux for ctrl tab or ctrl shift tab to navigate tabs
# https://github.com/alacritty/alacritty/issues/4451#issuecomment-1235088018
[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

# this is a hack to send raw characters to tmux to allow ctrl + num
# https://unix.stackexchange.com/a/96936
[[keyboard.bindings]]
chars = "\u001B[27;5;49~"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;50~"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;51~"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;52~"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;53~"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;54~"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;55~"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;56~"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;57~"
key = "Key9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;48~"
key = "Key0"
mods = "Control"


# unbind default search so I can use it in vim
[[keyboard.bindings]]
action = "ReceiveChar"
key = "f"
mods = "Control|Shift"

# unbind vi mode cause I use tmux
[[keyboard.bindings]]
action = "ReceiveChar"
key = "Space"
mods = "Control|Shift"

[general]
import = [
    "~/lib/external/alacritty-theme/themes/dracula.toml"
]

[terminal]
