# make it bigger
[font]
size = 22

[font.bold]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font Mono"
style = "Regular"

[general]
import = [
    "~/.config/alacritty/alacritty.toml"
]

[keyboard]
bindings = [
# Pasta
# for some reason manually re-binding paste on Linux messes up stuff
{ key = "v", mods = "Control|Shift", action = "PasteSelection"},

# Delete word
{ key= "Back", mods = "Control", chars = "\u001b\u007f" },

# Skip word left
{ key = "Left", mods = "Alt", chars = "\u001BB" }, # Skip word left
# { key = "Left", mods = "Alt", chars = "WordLeft" }, # Skip word left

# { key = "Left", mods = "Control", action = "PasteSelection"},

# Skip word right
{ key = "Right", mods = "Alt", chars = "\u001BF" },

# Delete line ??
# ,{ key= "Back", mods= "Command", chars= "\u0015" } # Delete line
]
