# make it bigger
[font]
size = 22

[font.bold]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font Mono"
style = "Regular"

# for some reason manually re-binding paste on Linux messes up stuff
[[keyboard.bindings]]
action = "PasteSelection"
key = "v"
mods = "Control|Shift"
